# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1ce6260ecff5db1650faa5073c53d2a759694ab5479cc62a7447786cc542eb1d44209de6e75ff019fda7309be7ad297495b7dd7b0cd38c69797713dc70d35d0

test:
  secret_key_base: 1fdfc4160e00aa144a9bafae627ab4301fc3810c694f897e1a8690c228009c381e926d08fa7cba01cc454ac8fc803c59beafee4ee619fd96f936e4e7f3b34125

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
